[GENERAL]
run_engine=openfpga_shell
power_analysis=false
spice_output=false
verilog_output=true
timeout_each_job=20*60
fpga_flow=vpr_blif
arch_variable_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/design_variables.yml

[OpenFPGA_SHELL]
openfpga_shell_template=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/generate_fabric.openfpga
openfpga_arch_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/openfpga_arch.xml
openfpga_sim_setting_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/efpga_12x12_sim_openfpga.xml
external_fabric_key_file=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/fabric_key.xml
openfpga_vpr_device_layout=12x12
openfpga_vpr_route_chan_width=40

[ARCHITECTURES]
arch0=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/vpr_arch.xml

[BENCHMARKS]
bench0=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/and.blif

[SYNTHESIS_PARAM]
bench0_top=and2
bench0_act=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/and.act
bench0_verilog=/home/ketan/OpenFPGA/openfpga_flow/tasks/sofa_hd_custom/and.v

[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]
